# Generated by Django 5.2 on 2025-06-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_agent",
            new_name="is_volunteer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_customer",
        ),
    ]
